/* 
 * File:   consts.h
 * Author: daniel
 *
 * Created on July 11, 2013, 11:16 AM
 */

#ifndef CONSTS_H
#define	CONSTS_H

#define MACHINE_WORD_LENGTH 20

#define LABEL_TOKEN ':'
#define COMMENT_TOKEN ';'
#define GUIDANCE_TOLEN '.'
#define REGISTER_NAME_PREFIX 'r'
#define REGISTER_NAME_PREFIX_LENGTH 1
#define MIN_REGISTER_ID 0
#define MAX_REGISTER_ID 7
#define IS_VALID_REGISTER_ID(id) ((id) >= MIN_REGISTER_ID && (id) <= MAX_REGISTER_ID)
#define REGISTER_NAME_LENGTH 2
#define OPCODE_CONTROL_PARAMETER_SEPERATOR '/'
#define OPCODE_CONTROL_PARAMETER_SEPERATOR_LENGTH 1
#define OPCODE_TYPE_AND_DBL_SEPERATOR ','
#define OPCODE_TYPE_AND_DBL_SEPERATOR_LENGTH 1
#define OPERAND_SEPERATOR ','
#define INSTANT_ADDRESSING_OPERAND_PREFIX '#'
#define INSTANT_ADDRESSING_OPERAND_PREFIX_LENGTH 1

#define DATA_GUIDANCE_TOKEN ".data"
#define DATA_GUIDANCE_TOKEN_LENGTH strlen(DATA_GUIDANCE_TOKEN)
#define STRING_GUIDANCE_TOKEN ".string"
#define STRING_GUIDANCE_TOKEN_LENGTH strlen(STRING_GUIDANCE_TOKEN)
#define ENTRY_GUIDANCE_TOKEN ".emtry"
#define ENTRY_GUIDANCE_TOKEN_LENGTH strlen(ENTRY_GUIDANCE_TOKEN)
#define EXTERN_GUIDANCE_TOKEN ".extern"
#define EXTERN_GUIDANCE_TOKEN_LENGTH strlen(EXTERN_GUIDANCE_TOKEN)

#define MAX_CODE_LINE_LENGTH 80
#define MAX_LABEL_LENGTH 30
#define MESSAGE_BUFFER_LENGTH 80

#define COMB_SOURCE_OPERAND_MASK 2
#define COMB_TARGET_OPERAND_MASK 1

#define EOL '\0'

#define DEBUG

#endif	/* CONSTS_H */

